name: Auto Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 75.101.205.200 >> ~/.ssh/known_hosts

      - name: Deploy to EC2 and restart PM2
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no bitnami@75.101.205.200 << 'EOF'
            cd ~/builderhub/my-solomate-be
            git pull origin main
            npm install
            pm2 restart ecosystem.config.js || pm2 start npm --name "solomate" -- start
          EOF
